import Head from "next/head";
import styles from "../styles/Home.module.css";

import Navbar from "../components/Navbar";

const Home = ({ data }) => {
  console.log({ data });
  return (
    <div className={styles.container}>
      <Head>
        <title>Humans of Sourcegraph</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/icon-32.png" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <h1 className={styles.title}>Sourcegraph </h1>
        <h3>Humans of Sourcegraph</h3>
        <h4>Familiarize yourself with our teammates and organization.</h4>
      </main>
    </div>
  );
};

export async function getServerSideProps() {
  const options = {
    method: "GET",
    headers: {
      Accept: "application/json",
      Authorization: "Basic ",
      "Access-Control-Allow-Origin": "*",
    },
  };

  const data = await fetch(
    "https://api.bamboohr.com/api/gateway.php/sourcegraph/v1/employees/directory",
    options
  )
    .then((response) => response.json())
    .catch((err) => console.error(err));

  return {
    props: {
      data,
    },
  };
}

export default Home;
