import Head from "next/head";
import styles from "../styles/Home.module.css";

import Navbar from "../components/Navbar";

const Home = () => {
  const options = {
    // mode: "no-cors",
    method: "GET",
    headers: {
      Accept: "application/json",
      Authorization: "Basic ",
    },
  };

  fetch(
    "https://api.bamboohr.com/api/gateway.php/sourcegraph/v1/employees/directory",
    options,
  )
    .then((response) => response.json())
    .then((response) => console.log(response))
    .catch((err) => console.error(err));
  return (
    <div className={styles.container}>
      <Head>
        <title>Humans of Sourcegraph</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/icon-32.png" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <h1 className={styles.title}>Sourcegraph </h1>
        <h3>Humans of Sourcegraph</h3>
        <h4>Familiarize yourself with our teammates and organization.</h4>
      </main>
    </div>
  );
};

export default Home;
